version: '3.1'

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data

  api:
    build:
        context: "./packages/api"
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
        - 5000:5000
    depends_on:
      - redis

  bot:
    build:
      context: "./packages/telegram-bot"
    restart: always

    env_file:
      - .env

  fetcher:
    build:
      context: "./packages/fetcher"
    restart: always

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # redis-insight:
  #   image: redis/redisinsight:latest
  #   restart: always
  #   ports:
  #     - 5540:5540
  #   volumes:
  #     - ./docker-data/redis-insight:/data
