version: '3.1'

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    volumes:
      - ./docker-data/redis-insight:/data